config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles

  resources :donations
  resources :companies, except: [:index, :show]

  get '/places/:place_id/metro' => 'places#metro', as: 'place_metro'

  #Admin
  namespace :admin do
    get "/", to: "admin#dashboard", as: "dashboard"
    get "articles", to: "articles#index", as: "articles"
    resources :users, only: [:index, :edit, :update]
  end
end

app/views/layouts/admin/_admin_head.slim
title Foods Sharing Admin Area
= stylesheet_link_tag  'admin', media: 'all', 'data-turbolinks-track' => 'reload'
= javascript_include_tag 'admin', 'data-turbolinks-track' => 'reload'
= csrf_meta_tags
link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"

app/views/layouts/admin/_admin_navbar.html.slim
nav.navbar.navbar-light.bg-faded.navbar-fixed-top
  button.navbar-toggler.hidden-sm-up type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"
  .collapse.navbar-toggleable-xs id="navbarResponsive"
    = link_to 'Foodsharing admin area', admin_dashboard_path, class: 'navbar-brand'
    .float-sm-right
      ul.nav.navbar-nav
        li.nav-item
          = link_to t('.dashboard'), admin_dashboard_path, class: 'nav-link'
        li.nav-item
          = link_to t('.home'), root_path, class: 'nav-link'
        li.nav-item
          - if user_signed_in?
            = link_to "#{t('.sign_out')} (#{current_user.email})", destroy_user_session_path, method: :delete, class: 'nav-link'
          - else
            = link_to t('.sign_in'), new_user_session_path, class: 'nav-link'

app/views/layouts/admin/_admin_sidebar.html.slim
h3 sidebar
ul.admin_sidebar
  li.admin_sidebar_item= link_to "Users", admin_users_path
  li.admin_sidebar_item= link_to "Articles", admin_articles_path