config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles

  resources :donations
  resources :companies, except: [:index, :show]

  get '/places/:place_id/metro' => 'places#metro', as: 'place_metro'

  #Admin
  namespace :admin do
    get "/", to: "admin#dashboard", as: "dashboard"
    get "articles", to: "articles#index", as: "articles"
    resources :users, only: [:index, :edit, :update]
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
  resourcify
  include Authority::Abilities # updatable_by?

  belongs_to :user
  belongs_to :place

  validates  :title, :description, :user_id, presence: true

  default_scope { order(created_at: :desc) }

  before_create :set_special
  before_validation :set_place, on: [:create, :update]

  private

  def set_special
    self.special = true if user.has_role? :cafe
  end

  def set_place
    return unless place_id.nil?
    city = City.find_or_create_by(name: nil)
    place = Place.find_or_create_by(city_id: city.id, name: nil)
    self.place = place
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :load_donation, only: [:show, :edit, :update, :destroy]
  before_action :authorize_donation, only: [:show, :edit, :destroy]

  def index
    if current_user.present? && current_user.can_specialize?(Donation, action_name)
      @donations = Donation.all
    else
      @donations = Donation.where(special: false)
    end
  end

  def show
  end

  def new
    @donation = Donation.new
  end

  def edit
  end

  def create
    @donation = Donation.new(donation_params.merge(user: current_user))
    authorize_donation
    if @donation.save
      redirect_to @donation
    else
      render :new
    end
  end

  def update
    @donation.attributes = donation_params
    authorize_donation
    if @donation.update(donation_params)
      redirect_to @donation
    else
      render :edit
    end
  end

  def destroy
    @donation.destroy
    redirect_to donations_path
  end

  private

  def load_donation
    @donation = Donation.find(params[:id])
  end

  def donation_params
    params.require(:donation).permit(:title, :description, :special, :pick_up_date, :place_id)
  end

  def authorize_donation
    authorize_action_for @donation
  end
end

app/helpers/donations_helper.rb
module DonationsHelper
  def current_place
    "г. #{@donation.place.city.name}, ст. м. #{@donation.place.name}"
  end
end

app/views/donations/_activities.html.slim
.divider
.section
  - @activities.each do |activity|
    .time_ago
      => time_ago_in_words activity.updated_at
      = I18n.t(".activity.ago")
    .activity
      strong=> activity.user.full_name
      => I18n.t(".activity.#{activity.action}")
      => link_to activity.donation.title, donation_path(activity.donation)
      /= activity.recipient
  end
.divider

app/views/donations/_donation.html.slim
div.row
  div.col-xs-12
  
    = link_to t('common.back'), donations_path, class: 'btn btn-outline-primary' 
    
    h5 = donation.title
    small = donation.created_at.strftime("%d.%m.%Y")
    - if donation.special?
      h6 = t('activerecord.attributes.donation.special') 
    
    p = donation.description
.row
  .col
    - if user_signed_in?
      =< link_to t('common.edit'), edit_donation_path(donation), class: 'btn btn-primary' if current_user.can_update?(donation)
      =< link_to t('common.destroy'), donation_path(donation), method: :delete, data: {confirm: t('common.confirm')}, class: 'btn btn-danger' if current_user.can_delete?(donation)

app/views/donations/_donations.html.slim
hr
div.row
  div.col-xs-12
    h5 = link_to donation.title, donation_path(donation)
    small = donation.created_at.strftime("%d.%m.%Y")
    p = donation.description

app/views/donations/_form.html.slim
.row
  .col-sm-8.offset-sm-2
    = link_to t('common.back'), donations_path, class: 'btn btn-outline-primary' 

    = form_for @donation do |f|
      = render 'common/errors', resource: @donation
      - if current_user.can_specialize?(Donation, action_name)
        .form-group
          = f.label :pick_up_date
          .form-group
            = f.datetime_select :pick_up_date, include_blank: true, class: 'form-control'
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control'

      .form-group
        = t('.place')
        .place
          -unless @donation.new_record? || @donation.place == nil
            strong= t('.your_place')
            =< current_place
        = select_tag 'city', options_from_collection_for_select(City.all, 'id', 'name'), class: 'city-select form-control', prompt: t('.choose_city')

      .form-group
        = select_tag 'donation[place_id]', {}, class: 'form-control'

      - if current_user.has_role?(:admin) && (action_name == 'new' || @donation.user == current_user)
        .form-group
          = f.label :special
          = f.check_box :special, class: 'form-control'

      .form-group
        = f.submit t('.submit', action: @donation.new_record? ? t('common.create') : t('common.update')), class: 'btn btn-primary'

app/views/donations/edit.html.slim
.row
  .col-12

    h3.text-sm-center = t('.title')
    == render 'form'

app/views/donations/index.html.slim
div.row
  h3 = t('.title')
  - if user_signed_in?
    p = link_to t('.new'), new_donation_path, class: 'btn btn-primary'
  div.col-md-9.col-xs-12
    = render partial: 'donations', collection: @donations, as: 'donation'
  div.col-md-3.col-xs-12
    = render partial: 'activities' unless @activities.nil?

app/views/donations/new.html.slim
.row
  .col-12

    h3.text-sm-center= t('.title')
    == render 'form'

app/views/donations/show.html.slim
div.row
  div.col-xs-12

    h3 = t('.title')
    = render @donation 