config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'omniauth_callbacks' }

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles

  resources :donations
  resources :companies, except: [:index, :show]

  get '/places/:place_id/metro' => 'places#metro', as: 'place_metro'

  #Admin
  namespace :admin do
    get "/", to: "admin#dashboard", as: "dashboard"
    get "articles", to: "articles#index", as: "articles"
    resources :users, only: [:index, :edit, :update]
  end
end

app/views/layouts/_footer.slim
footer
  div.container
    div.row
      div.col-md-6
        h5 = t('.about_header')
        p = t('.about')
      div.col-md-3
        h5 = t('.social_networks')
        ul
          li
            a href="https://vk.com/sharingfood" target="_blank"
              | VK
      div.col-md-3
        h5 = t('.source_code')
        a href="https://github.com/rails-up/foodsharing" target="_blank"
          span GitHub

app/views/layouts/_head.slim
title Foods Sharing
= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
= csrf_meta_tags
link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"

app/views/layouts/_navbar.slim
nav.navbar.navbar-light.bg-faded.navbar-fixed-top
  button.navbar-toggler.hidden-sm-up type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"
  div.collapse.navbar-toggleable-xs id="navbarResponsive"
    = link_to 'Foodsharing', root_path, class: 'navbar-brand'
    div.float-sm-right
      ul.nav.navbar-nav
        = render "layouts/navlink"

app/views/layouts/_navlink.slim
li.nav-item
  = link_to t('.donations'), donations_path, class: 'nav-link'
li.nav-item
  = link_to t('.articles'), articles_path, class: 'nav-link'
li.nav-item
  - if user_signed_in?
    = link_to "#{t('.sign_out')} (#{current_user.email})", destroy_user_session_path, method: :delete, class: 'nav-link'  
  - else
    = link_to t('.sign_in'), new_user_session_path, class: 'nav-link'

app/views/layouts/_notice.slim
- if flash[:notice]
  p#flash_notice.notification = flash[:notice]
  = javascript_tag "$('#flash_notice').effect('highlight',{},1000);"
- if flash[:alert]
  p#flash_alert.notification = flash[:alert]
  = javascript_tag "$('#flash_alert').effect('highlight',{},1000);"  
- if flash[:error] || flash[:errors]
  p#flash_errors.notification = flash[:error] || flash[:errors]
  = javascript_tag "$('#flash_errors').effect('highlight',{},1000);"
- flash[:error] = flash[:errors] = flash[:notice] = nil

app/views/layouts/admin.html.slim
doctype html
html
  head
    = render "layouts/admin/admin_head"
  body
    = render "layouts/admin/admin_navbar"
    = render "layouts/notice"
    main role="main"
      .container
        .row
          .col-md-2.col-xs-12
            = render "layouts/admin/admin_sidebar"
          .col-md-10.col-xs-12
            = yield

  = debug(params) if Rails.env.development?

app/views/layouts/application.html.slim
doctype html
html
  head
    = render "layouts/head"
  body
    = render "layouts/navbar"
    = render "layouts/notice"
    main role="main"
      article.container 
        = yield
    = render "layouts/footer"

    = debug(params) if Rails.env.development?

app/views/layouts/welcome.html.slim
doctype html
html
  head
    = render "layouts/head"
  body
    = render "layouts/navbar"
    = render "layouts/notice"
    main role="main"
      article 
        = yield
    = render "layouts/footer"